name: Build CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.14.2]
        platform: [ubuntu-18.04]
        arch: [x64]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checking out sources
        uses: actions/checkout@master

      # Install & Cache Qt---------------------------------------
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}
      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2.5.0
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          mirror: "http://mirrors.ocf.berkeley.edu/qt/"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      
      - name: Linux - ${{ matrix.qt_version }} - Generate Dependencies and Build
        if: matrix.platform == 'ubuntu-18.04'
        shell: bash
        env:
          CC: /usr/bin/gcc-9
          CXX: /usr/bin/g++-9
        run: |
          sudo apt install libgl-dev libx11-dev libxkbcommon-x11-dev
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=./AppDir/usr -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cmake --install .
